"""Initial migration

Revision ID: 6665a3f74494
Revises: 
Create Date: 2025-02-19 00:25:34.973541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6665a3f74494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('home_address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('home_longitude', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('home_latitude', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'timestamp')
    # ### end Alembic commands ###
    op.drop_column('users', 'home_address')
    op.drop_column('users', 'home_longitude')
    op.drop_column('users', 'home_latitude')
